name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, fix ]
  pull_request:
    branches: [ dev, main ]

# Даём права на запись для деплоя
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start HTTP server
        run: |
          python -m http.server 8000 &
          sleep 3
      - name: Run tests
        run: pytest tests/ --html=report.html --self-contained-html
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v4   # обновим до v4 (работает с Node.js 20)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages